
version: 2

jobs:
  build:
    working_directory: ~/test
    docker: # run the steps with Docker
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install
          command: npm i
      - run:
          name: npm test
          command: |
              nodejs -v
              npm -v
              npm run lint
              npm run test:report